"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Item = { id:number; name:string|null; mode:"AI"|"HUMAN"; last_message:string|null; order_id:number|null; order_number:string|null; order_status:string|null; waitingMinutes:number; reason:string };
type Detail = { conversationId:number; messages:Array<{id:number;role:string;content:string;created_at:number}>; order:null|Record<string, unknown> & {id:number}; history:Array<{id:number;new_status:string;occurred_at:number}>; windowOpen:boolean };

export default function TrabajoPage() {
  const [items,setItems]=useState<Item[]>([]), [detail,setDetail]=useState<Detail|null>(null), [selected,setSelected]=useState<number|undefined>(), [error,setError]=useState("");
  const load=useCallback(async(id?:number)=>{ const r=await fetch(`/api/workspace${id?`?conversationId=${id}`:""}`); if(r.status===401)return location.assign("/login"); const b=await r.json(); if(!r.ok)return setError(b.error); setItems(b.items); setDetail(b.selected); setSelected(b.selected?.conversationId); },[]);
  useEffect(()=>{void load();},[load]);
  async function act(url:string, body:Record<string,unknown>){setError("");const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok){setError(b.error);return false;}await load(selected);return true;}
  async function promptAction(action:string,label:string){const value=window.prompt(label);if(value)await act("/api/workspace/action",{action,conversationId:selected,orderId:detail?.order?.id,value});}
  async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(await act(`/api/messages/${selected}`,{content:form.get("message")}))e.currentTarget.reset();}
  return <main className="min-h-screen bg-brand-bg p-4 md:p-6">
    <header className="mx-auto mb-5 flex max-w-[1500px] items-end justify-between"><div><div className="text-[12px] font-semibold uppercase tracking-[.14em] text-brand-accent">Casamable</div><h1 className="text-[26px] font-semibold">Atención al cliente</h1><p className="text-brand-muted">Conversaciones que necesitan una persona, primero las que más esperan.</p></div><button onClick={()=>fetch('/api/auth/logout',{method:'POST'}).then(()=>location.assign('/login'))} className="text-[13px] font-medium">Cerrar sesión</button></header>
    {error&&<div role="alert" className="mx-auto mb-3 max-w-[1500px] rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
    <div className="mx-auto grid max-w-[1500px] overflow-hidden rounded-2xl border border-brand-border bg-white shadow-[var(--shadow-card)] md:grid-cols-[320px_minmax(360px,1fr)_360px] min-h-[76vh]">
      <section className="border-r border-brand-border"><h2 className="border-b p-4 text-[13px] font-semibold">Bandeja · {items.length}</h2>{items.map(i=><button key={i.id} onClick={()=>void load(i.id)} className={`block w-full border-b p-4 text-left ${selected===i.id?'bg-brand-surface-2':''}`}><div className="flex justify-between gap-2"><strong>{i.name||'Cliente'}</strong><span className="text-[12px] text-brand-tertiary">{i.waitingMinutes} min</span></div><div className="mt-1 text-[12px] text-brand-muted">Pedido {i.order_number||'—'} · {i.order_status||'sin pedido'}</div><p className="mt-2 truncate text-[13px]">{i.last_message||'Sin mensajes'}</p><span className="mt-2 inline-flex rounded-full bg-amber-50 px-2 py-1 text-[11px] text-amber-700">{i.reason}</span></button>)}</section>
      <section className="flex min-h-[600px] flex-col"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">Conversación</h2>{detail&&<button onClick={()=>act(`/api/mode/${selected}`,{mode:items.find(i=>i.id===selected)?.mode==='HUMAN'?'AI':'HUMAN'})} className="rounded-lg bg-brand-text px-3 py-2 text-[13px] text-white">{items.find(i=>i.id===selected)?.mode==='HUMAN'?'Devolver al bot':'Atender'}</button>}</div><div className="chat-wallpaper flex-1 space-y-2 overflow-auto p-5">{detail?.messages.map(m=><div key={m.id} className={`max-w-[78%] rounded-xl px-3 py-2 ${m.role==='user'?'bg-white':'ml-auto bg-[#d9fdd3]'}`}><p>{m.content}</p><time className="text-[10px] text-brand-tertiary">{new Date(m.created_at*1000).toLocaleString('es-ES')}</time></div>)}</div>{detail&&!detail.windowOpen?<div className="border-t bg-amber-50 p-4 text-[13px]">La ventana de 24 h está cerrada. Escala el caso a Pedro.</div>:detail&&<form onSubmit={send} className="flex gap-2 border-t p-3"><input name="message" required placeholder="Escribe un mensaje" className="h-11 flex-1 rounded-lg border px-3"/><button className="rounded-lg bg-brand-text px-4 text-white">Enviar</button></form>}</section>
      <aside className="border-l border-brand-border p-5"><h2 className="font-semibold">Ficha del pedido</h2>{detail?.order?<><dl className="mt-4 space-y-3 text-[13px]">{Object.entries(detail.order).filter(([k])=>k!=='id').map(([k,v])=><div key={k}><dt className="text-[11px] uppercase text-brand-tertiary">{labels[k]||k}</dt><dd>{String(v??'—')}</dd></div>)}</dl><div className="mt-5 grid gap-2"><button onClick={()=>promptAction('correct_address','Dirección corregida')} className="rounded-lg border p-2">Guardar dirección corregida</button><button onClick={()=>promptAction('delivery_note','Nota para el repartidor')} className="rounded-lg border p-2">Nota para el repartidor</button><button onClick={()=>act(`/api/orders/${detail.order?.id}/action`,{action:'resend'})} className="rounded-lg border p-2">Reenviar confirmación</button><button onClick={()=>promptAction('resolve','Nota de resolución (obligatoria)')} className="rounded-lg bg-brand-text p-2 text-white">Marcar resuelto</button><button onClick={()=>promptAction('escalate','Motivo para Pedro')} className="rounded-lg border border-amber-600 p-2 text-amber-700">Escalar a Pedro</button></div><h3 className="mt-6 text-[12px] font-semibold">Historial de estados</h3><ol className="mt-2 space-y-2 text-[12px]">{detail.history.map(h=><li key={h.id}>{h.new_status} · {new Date(h.occurred_at*1000).toLocaleDateString('es-ES')}</li>)}</ol></>:<p className="mt-4 text-brand-muted">No hay un pedido vinculado.</p>}</aside>
    </div>
  </main>;
}
const labels:Record<string,string>={orderNumber:'Pedido',customerName:'Nombre',status:'Estado',product:'Producto',units:'Unidades',amount:'Importe contra reembolso',currency:'Moneda',address:'Dirección',city:'Localidad',postalCode:'CP',carrier:'Transportista',trackingNumber:'Seguimiento',orderedAt:'Fecha del pedido',proposedAddress:'Dirección propuesta',deliveryNote:'Nota del repartidor'};
