"use client";
import { useEffect, useState } from "react";
import type { ProductSignal, ProviderStatus, ResearchSession, WatchlistItem } from "@/lib/product-intelligence/types";

export default function ProductIntelligencePanel() {
  const [query, setQuery] = useState(""); const [sessions, setSessions] = useState<ResearchSession[]>([]); const [provider, setProvider] = useState<ProviderStatus>();
  const [signals, setSignals] = useState<ProductSignal[]>([]); const [watchlist, setWatchlist] = useState<WatchlistItem[]>([]); const [running, setRunning] = useState(false); const [error, setError] = useState("");
  async function refresh() { const response = await fetch("/api/product-intelligence", { cache: "no-store" }); if (response.ok) { const data = await response.json() as { sessions: ResearchSession[]; provider: ProviderStatus; signals: ProductSignal[]; watchlist: WatchlistItem[] }; setSessions(data.sessions); setProvider(data.provider); setSignals(data.signals); setWatchlist(data.watchlist); } }
  useEffect(() => { void refresh(); }, []);
  async function testMeta() { setRunning(true); setError(""); try { await fetch("/api/product-intelligence/meta-health", { method: "POST" }); await refresh(); } catch { setError("No se pudo comprobar Meta"); } finally { setRunning(false); } }
  async function start(manual: boolean) { if (manual && !query.trim()) return setError("Escribe una palabra o frase."); setRunning(true); setError(""); try { const response = await fetch("/api/product-intelligence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(manual ? { query } : {}) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "No se pudo iniciar"); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Error inesperado"); } finally { setRunning(false); } }
  async function watch(productId: string, action: "watchlist" | "watchlist-remove", status = "MONITORING") { await fetch("/api/product-intelligence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, productId, watchlistStatus: status }) }); await refresh(); }
  const current = sessions[0]; const metaReady = provider?.code === "META_CONNECTED";
  const metrics: Array<[string, string | number]> = [["Session ID", current?.id?.slice(0, 8) ?? "—"], ["Mode", current?.mode ?? "—"], ["Status", current?.status ?? "—"], ["Root Query", current?.rootQuery ?? "AUTO"], ["Queries processed", current?.queriesProcessed ?? 0], ["Queries pending", current?.queries.filter((item) => item.status === "PENDING").length ?? 0], ["Ads found", current?.adsScanned ?? 0], ["Advertisers", current?.advertisersFound ?? 0], ["Products", current?.productsFound ?? 0], ["Qualified", current?.qualifiedProductsFound ?? 0], ["Depth", current?.currentDepth ?? 0]];
  return <section className="h-full overflow-y-auto p-6"><div className="mx-auto max-w-6xl space-y-5">
    <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand-gold">Product Intelligence</p><h1 className="font-display text-3xl text-brand-text">Cazador de productos ganadores</h1><p className="mt-1 text-sm text-brand-muted">Solo lectura. Nunca crea ni modifica campañas.</p></div>
    <div className="rounded-xl border border-brand-border bg-brand-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-brand-text">Meta Ad Library</h2><p className="mt-1 text-xs text-brand-muted">Provider: META_AD_LIBRARY · Configuration: {provider?.configured ? "CONFIGURED" : "NOT CONFIGURED"} · Authorization: {provider?.authorization ?? "UNKNOWN"}</p><p className="mt-1 text-xs text-brand-muted">API: {provider?.apiVersion ?? "—"} · Last attempt: {provider?.lastConnectionAttempt ?? "none"} · Last success: {provider?.lastSuccessfulScan ?? "none"}</p>{provider?.reason && <p className="mt-1 text-xs text-amber-400">{provider.reason}</p>}</div><button disabled={running} onClick={() => void testMeta()} className="rounded-lg border border-brand-gold px-4 py-2 text-xs font-semibold text-brand-gold disabled:opacity-50">Probar conexión Meta</button></div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-brand-border bg-brand-surface p-5"><h2 className="font-semibold text-brand-text">Research keyword</h2><p className="mt-1 text-xs text-brand-muted">La primera búsqueda conserva exactamente tu texto.</p><div className="mt-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="almohada cervical" className="min-w-0 flex-1 rounded-lg border border-brand-border bg-brand-bg px-3 py-2 text-sm text-brand-text outline-none focus:border-brand-gold"/><button disabled={running || !metaReady} onClick={() => void start(true)} className="rounded-lg bg-brand-gold px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">Investigar</button></div></div><div className="rounded-xl border border-brand-gold/30 bg-brand-surface p-5"><h2 className="font-semibold text-brand-text">Auto Hunt — Safe Test</h2><p className="mt-1 text-xs text-brand-muted">5 semillas · 2 páginas · profundidad 2 · máximo 20 llamadas · manual.</p><p className="mt-2 text-xs font-semibold text-amber-400">{metaReady ? "READY" : "WAITING_FOR_META_AUTHORIZATION"}</p><button disabled={running || !metaReady} onClick={() => void start(false)} className="mt-4 rounded-lg border border-brand-gold px-4 py-2 text-sm font-semibold text-brand-gold disabled:opacity-50">Auto Hunt — Safe Test</button></div></div>
    {error && <p className="rounded-lg border border-red-800 bg-red-950/30 p-3 text-sm text-red-300">{error}</p>}
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{metrics.map(([label, value]) => <div key={label} className="rounded-xl border border-brand-border bg-brand-surface p-3"><div className="text-[10px] text-brand-muted">{label}</div><div className="mt-1 truncate text-sm font-semibold text-brand-text">{value}</div></div>)}</div>
    {current?.queries.length ? <div className="rounded-xl border border-brand-border bg-brand-surface p-5"><h2 className="mb-3 font-semibold text-brand-text">Query tree</h2>{current.queries.slice(0, 30).map((item) => <div key={item.id} style={{ marginLeft: `${item.depth * 18}px` }} className="mb-1 flex justify-between rounded bg-brand-bg px-3 py-2 text-xs"><span className="text-brand-text">{item.depth ? "↳ " : ""}{item.displayQuery}</span><span className="text-brand-muted">{item.source} · {item.status} · score {item.queryScore} · {item.resultsCount} results</span></div>)}</div> : null}
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-brand-border bg-brand-surface p-5"><h2 className="font-semibold text-brand-text">Señales</h2>{signals.length ? signals.slice(-10).reverse().map((signal) => <p key={signal.id} className="mt-2 text-xs text-brand-muted">{signal.type}: {signal.message}</p>) : <p className="mt-2 text-xs text-brand-muted">Sin señales reales todavía.</p>}</div><div className="rounded-xl border border-brand-border bg-brand-surface p-5"><h2 className="font-semibold text-brand-text">Watchlist</h2>{watchlist.length ? watchlist.map((item) => <p key={item.productId} className="mt-2 text-xs text-brand-muted">{item.productId} · {item.status}</p>) : <p className="mt-2 text-xs text-brand-muted">Vacía. No se generan candidatos falsos.</p>}</div></div>
    {current?.products.length ? <div className="rounded-xl border border-brand-border bg-brand-surface p-5"><h2 className="mb-3 font-semibold text-brand-text">Product dossiers</h2>{current.products.map((product) => <div key={product.id} className="mb-3 rounded-lg bg-brand-bg p-4"><div className="flex justify-between"><span className="font-semibold text-brand-text">{product.name}</span><span className="text-brand-gold">{product.opportunityScore}/100 · confidence {product.confidence}</span></div><p className="mt-1 text-xs text-brand-muted">{product.lifecycle} · {product.recommendation} · {product.activeAds} ads · {product.advertiserCount} advertisers · missing: {product.missingData?.join(", ") || "none"}</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(product.scoreBreakdown).map(([key, value]) => <span key={key} className="rounded bg-brand-surface px-2 py-1 text-[10px] text-brand-muted">{key}: {value > 0 ? "+" : ""}{value}</span>)}</div><div className="mt-3 flex gap-2"><button onClick={() => void watch(product.id, "watchlist")} className="text-xs text-brand-gold">Add to watchlist</button><button onClick={() => void watch(product.id, "watchlist", "PAUSED")} className="text-xs text-brand-muted">Pause monitoring</button><button onClick={() => void watch(product.id, "watchlist-remove")} className="text-xs text-brand-muted">Remove</button></div></div>)}</div> : null}
  </div></section>;
}
