import type{ProductCandidate}from"../hunter/types";import{benefits}from"./sections/benefits";import{closing}from"./sections/closing";import{contains}from"./sections/contains";import{faq}from"./sections/faq";import{footer}from"./sections/footer";import{guarantee}from"./sections/guarantee";import{header}from"./sections/header";import{hero}from"./sections/hero";import{hardProof}from"./sections/proof";import{reviews}from"./sections/reviews";import{steps}from"./sections/steps";import{stickybar}from"./sections/stickybar";import{topbar}from"./sections/topbar";import{trust}from"./sections/trust";import{variants}from"./sections/variants";
type Render=(c:ProductCandidate)=>string;
// El ritmo editorial cambia por categoría, pero las puertas de evidencia mandan dentro de cada render.
export const COMPOSITION_RULES:Record<string,Render[]>={
  cuidado:[topbar,header,hero,trust,reviews,benefits,contains,steps,hardProof,variants,guarantee,faq,closing,footer,stickybar],
  hogar:[topbar,header,hero,trust,benefits,hardProof,steps,variants,reviews,contains,guarantee,faq,closing,footer,stickybar],
  default:[topbar,header,hero,trust,benefits,steps,reviews,hardProof,variants,guarantee,faq,closing,footer,stickybar],
};
export function compositionFor(c:ProductCandidate):string[]{const key=(c.category??"").toLowerCase(),rules=key.includes("cuidado")?COMPOSITION_RULES.cuidado:key.includes("hogar")||key.includes("ropa")?COMPOSITION_RULES.hogar:COMPOSITION_RULES.default;return rules.map(fn=>fn(c)).filter(Boolean);}
export function composeLanding(c:ProductCandidate):string{const sections=compositionFor(c).join("");return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${c.name??"Producto"} · Casamable</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;600;700&family=Fraunces:wght@600;700&display=swap" rel="stylesheet"><style>
:root{--paper:#F7F4EC;--ink:#18211D;--soft:#59635E;--accent:#D45735;--accent-dark:#A93E23;--line:#D9D5CA;--font-display:"Fraunces",Georgia,serif;--font-body:"DM Sans",Arial,sans-serif;--page:24px;--title:40px;--heading:29px;--text:15px;--button:14px;--section:56px;--radius:20px}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:84px;overflow-x:clip}body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--font-body);font-size:var(--text)}.wrap{max-width:1180px;margin:0 auto;padding:var(--section) var(--page)}h1,h2,h3,p{margin-top:0}h1,h2{font-family:var(--font-display)}h1{font-size:var(--title);line-height:1.02}h2{font-size:var(--heading)}.btn{border:0;border-radius:999px;background:var(--accent);color:#FFFFFF;padding:14px 22px;font-size:var(--button);font-weight:700;white-space:nowrap}.media{min-height:260px;aspect-ratio:4/3;border:2px dashed var(--line);border-radius:var(--radius)}svg{width:20px;height:20px}.hero__grid,.benefits__grid,.variants__grid,.trust__grid,.reviews__grid,.proof__grid,.contains__grid{display:grid;gap:24px}.hero__price{font-size:28px;font-weight:700}.benefits__item,.variants__item,.reviews article,.proof article{border:1px solid var(--line);border-radius:var(--radius);padding:22px}.trust,.proof--dark,.closing--dark{background:var(--ink);color:#FFFFFF}.topbar{text-align:center;padding:10px 24px;background:var(--accent);color:#FFFFFF}.topbar p{margin:0}.header__row{display:flex;align-items:center;justify-content:space-between;padding-top:14px;padding-bottom:14px}.faq details{border-bottom:1px solid var(--line);padding:18px 0}.guarantee{background:#E8DDC8}.closing{text-align:center}.footer{text-align:center}.buybar{position:fixed;z-index:10;left:12px;right:12px;bottom:12px;display:flex;align-items:center;justify-content:space-between;padding:10px 12px;padding-bottom:calc(10px + env(safe-area-inset-bottom));background:#FFFFFF;border:1px solid var(--line);border-radius:16px;transform:translateY(160%);visibility:hidden;transition:transform 220ms ease}.buybar--visible{transform:translateY(0);visibility:visible}@media (min-width:750px){:root{--page:32px;--title:64px;--heading:43px;--text:17px;--button:16px;--section:82px}.hero__grid{grid-template-columns:6fr 5fr}.benefits__grid,.variants__grid,.reviews__grid,.proof__grid{grid-template-columns:repeat(3,1fr)}.trust__grid,.contains__grid{grid-template-columns:repeat(2,1fr)}}@media (min-width:990px){.wrap{max-width:1280px}.buybar{display:none}}
</style></head><body><section class="symbols" data-bloque="iconos" hidden><svg><defs><symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6" fill="none" stroke="currentColor" stroke-width="2"/></symbol></defs></svg></section>${sections}</body></html>`;}
