import fs from "node:fs"; import path from "node:path";
const safe=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,20)||"bloque";
const visibleTexts=(html:string)=>[...html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"").matchAll(/>([^<]+)</g)].map(m=>m[1].replace(/\s+/g," ").trim()).filter(Boolean);
const strip=(html:string)=>html.replace(/<!--[\s\S]*?-->/g,"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"").replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,"");
function schema(name:string,texts:string[],media:boolean){const settings:any[]=[{type:"color",id:"color_fondo",label:"Color de fondo",default:"#F7F4EC"},{type:"color",id:"color_texto",label:"Color del texto",default:"#18211D"},{type:"range",id:"padding_superior",label:"Padding superior",min:0,max:120,step:4,unit:"px",default:80},{type:"range",id:"padding_superior_movil",label:"Padding superior móvil",min:0,max:120,step:4,unit:"px",default:56},{type:"range",id:"padding_inferior",label:"Padding inferior",min:0,max:120,step:4,unit:"px",default:80},{type:"range",id:"padding_inferior_movil",label:"Padding inferior móvil",min:0,max:120,step:4,unit:"px",default:56},{type:"range",id:"tamano_titulo",label:"Título escritorio",min:20,max:80,step:2,unit:"px",default:42},{type:"range",id:"tamano_titulo_movil",label:"Título móvil",min:16,max:60,step:2,unit:"px",default:28},{type:"range",id:"tamano_texto",label:"Texto escritorio",min:12,max:24,step:1,unit:"px",default:16},{type:"range",id:"tamano_texto_movil",label:"Texto móvil",min:12,max:24,step:1,unit:"px",default:15},{type:"range",id:"tamano_boton",label:"Botón escritorio",min:12,max:22,step:1,unit:"px",default:16},{type:"range",id:"tamano_boton_movil",label:"Botón móvil",min:12,max:22,step:1,unit:"px",default:14},...texts.map((t,i)=>({type:"text",id:`texto_${i+1}`,label:`Texto ${i+1}`,default:t.slice(0,200)}))];if(media)settings.push({type:"image_picker",id:"imagen",label:"Imagen"});return{name:name.slice(0,25),settings,presets:[{name:name.slice(0,25)}]};}
function liquidFor(name:string,source:string):string{const texts=visibleTexts(source),media=/class=["'][^"']*\bmedia\b/i.test(source),root=safe(name);let n=0;let markup=strip(source).replace(/^<section\b[^>]*>|<\/section>$/gi,"").replace(/>([^<]+)</g,(all,t)=>{if(!t.trim())return all;n++;return `>{{ section.settings.texto_${n} }}<`;}).replace(/<div([^>]*\bmedia\b[^>]*)>[\s\S]*?<\/div>/gi,media?`{% if section.settings.imagen != blank %}{{ section.settings.imagen | image_url: width: 1500 | image_tag: class: '${root}__imagen' }}{% else %}<div class="${root}__ph"></div>{% endif %}`:`<div class="${root}__ph"></div>`);markup=markup.replace(/class=(['"])([^'"]*)\1/g,(_m,q,classes)=>`class=${q}${String(classes).split(/\s+/).map((c:string)=>c?`${root}__${safe(c)}`:"").join(" ")}${q}`);const id="#shopify-section-{{ section.id }}";return `{%- style -%}
${id} .${root}{--tamano-titulo:{{ section.settings.tamano_titulo_movil }}px;--tamano-texto:{{ section.settings.tamano_texto_movil }}px;--tamano-boton:{{ section.settings.tamano_boton_movil }}px;background:{{ section.settings.color_fondo }};color:{{ section.settings.color_texto }};padding-top:{{ section.settings.padding_superior_movil }}px;padding-bottom:{{ section.settings.padding_inferior_movil }}px}
${id} .${root} h1,${id} .${root} h2{font-family:inherit;color:inherit;font-size:var(--tamano-titulo)}
${id} .${root}{font-size:var(--tamano-texto)}
${id} .${root} button{font:inherit;font-size:var(--tamano-boton)}
${id} .${root}__ph{min-height:260px;aspect-ratio:4/3;border:2px dashed currentColor}
@media (min-width:750px){${id} .${root}{--tamano-titulo:{{ section.settings.tamano_titulo }}px;--tamano-texto:{{ section.settings.tamano_texto }}px;--tamano-boton:{{ section.settings.tamano_boton }}px;padding-top:{{ section.settings.padding_superior }}px;padding-bottom:{{ section.settings.padding_inferior }}px}}
{%- endstyle -%}
<div class="${root} ${root}-{{ section.id }}">${markup}</div>
{% schema %}
${JSON.stringify(schema(name,texts,media),null,2)}
{% endschema %}
`;}
export function convertLanding(html:string,outDir:string,project="Casamable"):string[]{fs.mkdirSync(outDir,{recursive:true});const sections=[...html.matchAll(/<section\b[^>]*data-bloque=["']([^"']+)["'][^>]*>[\s\S]*?<\/section>/gi)],files:string[]=[];for(const m of sections){const file=path.join(outDir,`${project}-${safe(m[1])}.liquid`);fs.writeFileSync(file,liquidFor(m[1],m[0]),"utf8");files.push(file)}const fonts=/<link[^>]+fonts\.googleapis\.com[^>]*>/i.exec(html)?.[0]??"";const fontFile=path.join(outDir,`${project}-Tipografias.html`);fs.writeFileSync(fontFile,fonts,"utf8");files.push(fontFile);return files;}
